openapi: '3.0.0'
info:
  title: Viber
  description: |
    Conversations allows you to easily send messages to your customers via Viber.

    **Channel specific pre-conditions**

    - *Viber* : A Viber Service id is required in order to use this channel. Please [request access here](https://www.tyntec.com/form-conversational-api-viber-business)

    Viber defines different service types and capabilities. The service types limit the possible content combinations.

    The following content / service type combinations are valid

    | Service Type | Text | Image | Text & Button | Text & Button & Image |
    | ---: | :---: | :---: | :---: | :---: |
    | One way | ✔ | ✔ | ✔ | ✔ |
    | Two way | ✔ | ✔ | ✔ | ✔ |
    | Session | ✔ | ✔ | ❌ | ❌ |

  contact:
    name: tyntec API Support
    url: http://www.tyntec.com/support
    email: support@tyntec.com
  version: '3.0'
  x-repository: https://github.com/tyntec/api-collection/blob/master/conversations
  x-specification-file: viber.yaml
  x-major-version: v3
servers:
  - url: https://api.tyntec.com/conversations/v3
security:
  - ApiKeyAuth: [ ]
tags:
  - name: "Messaging"
    description: |
      In this section we guide you on how to send messages, get information about the status and the events happening during the delivery.
  - name: "Service IDs"
    description: |
      List all Service IDs configured for your API account.
  - name: "Callback configuration"
    description: |
      In this section, we guide you on how to configure the callbacks on a per channel bases.
paths:
  /messages:
    post:
      operationId: sendMessage
      summary: Send a message
      tags:
        - "Messaging"
      description: Send messages via this path.
      requestBody:
        description: The message you would like to send
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        202:
          $ref: '#/components/responses/MessageResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /bulks:
    post:
      operationId: sendABulkMessage
      summary: Send a bulk message
      tags:
        - "Messaging"
      description: Send bulk messages. Bulk messages are defined as ordered messages to **one** receiver.
      requestBody:
        description: The message bulk you would like to send
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkMessageRequest'
      responses:
        202:
          $ref: '#/components/responses/BulkMessageResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /configurations/channels/viber:
    get:
      tags:
        - "Service IDs"
      summary: List Service IDs
      operationId: listAllViberChannels
      description: List all Viber channels available to your API account
      responses:
        200:
          $ref: '#/components/responses/ListAllViberChannelsResponse'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /configurations/channels/viber/service-ids/{service-id}:
    parameters:
      - $ref: '#/components/parameters/ServiceId'
    get:
      tags:
        - "Service IDs"
      summary: Read a configuration
      operationId: getViberChannelConfig
      description: Returns the specific channel configuration
      responses:
        200:
          $ref: '#/components/responses/ViberChannelResponse'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /configurations/channels/viber/service-ids/{service-id}/callbacks:
    parameters:
      - $ref: '#/components/parameters/ServiceId'
    put:
      tags:
        - "Callback configuration"
      summary: Update the callback
      operationId: updateViberChannelCallback
      description: Update the callback settings of a specific viber channel.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChannelCallback'
      responses:
        200:
          $ref: '#/components/responses/ViberChannelResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
components:
  parameters:
    ServiceId:
      name: service-id
      in: path
      required: true
      description: Service ID used of a Viber Channel.
      schema:
        type: integer
        minLength: 4
        maxLength: 15
      example: 4923147790717
  responses:
    MessageResponse:
      description: Response after the server has accepted the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MessageResponse'
    BulkMessageResponse:
      description: Response after the server has accepted the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BulkMessageResponse'
    Default:
      description: Default response in case of any other error. Please check the error object for details
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    BadRequest:
      description: The request does not match our expectations. Please check the Problems object for details
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            status: 400
            violations: [
              {
                field: validate.request.content.contentType,
                message: must not be empty
              }
            ]
            title: Constraint Violation
    Forbidden:
      description: You are attempting to use a number that is not assigned to your account
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            type: https://httpstatuses.com/403
            title: Forbidden
            status: 403
    ListAllViberChannelsResponse:
      description: A list of Viber channel configurations
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ViberChannelResponses'
    ViberChannelResponse:
      description: A Viber channel configuration
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ViberChannelResponse'
  schemas:
    Problem:
      $ref: './common.yaml#/components/schemas/Problem'
    MessageResponse:
      $ref: './common.yaml#/components/schemas/MessageResponse'
    BulkMessageResponse:
      $ref: './common.yaml#/components/schemas/BulkMessageResponse'
    MessageRequest:
      type: object
      description: The message you would like to send
      required:
        - to
        - channel
        - from
        - messagePurpose
      properties:
        to:
          type: string
          description: |
            The receipient of the messages
            The format depends on the specific channel
          example: "+1233423454"
        from:
          type: string
          description: |
            The Viber service id the message origins from
          example: "+1233423454"
        messagePurpose:
          type: string
          description: The purpose of the message
          enum:
            - promotion
            - transaction
        channel:
          type: string
          description: Channel selected for delivery.
          example: viber
          items:
            type: string
            enum:
              - viber
        overrides:
          $ref: 'common.yaml#/components/schemas/MessageRequestOverrides'
        context:
          type: string
          description: Context for this particular message
          maxLength: 125
        content:
          oneOf:
            - $ref: '#/components/schemas/ViberTextContent'
            - $ref: '#/components/schemas/ViberImageContent'
            - $ref: '#/components/schemas/ViberComponentsContent'
      example:
        to: "+123234234"
        from: "545345345"
        channel:  "viber"
        messagePurpose: "promotion"
        content:
          contentType: text
          text: A simple text message
    BulkMessageRequest:
      type: object
      description: The bulk of messages you would like to send
      required:
        - to
        - channel
        - from
        - messages
        - messagePurpose
      properties:
        to:
          type: string
          description: |
            The receipient of the messages
            The format depends on the specific channel
          example: "+1233423454"
        from:
          type: string
          description: |
            The sender of the messages. The format depends on the specific channel.
          example: "+1233423454"
        messagePurpose:
          type: string
          description: The purpose of the message
          enum:
            - promotion
            - transaction
        channel:
          type: string
          description: Channel selected for delivery.
          example: viber
          items:
            type: string
            enum:
              - viber
        messages:
          type: array
          maxItems: 20
          minItems: 2
          items:
            - $ref: '#/components/schemas/ViberTextContent'
            - $ref: '#/components/schemas/ViberImageContent'
            - $ref: '#/components/schemas/ViberComponentsContent'
    ViberTextContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - text
        text:
          type: string
          maxLength: 3000
    ViberImageContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - image
        image:
          $ref: '#/components/schemas/ViberImage'
    ViberButtonContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - button
        button:
          $ref: '#/components/schemas/ViberButton'
    ViberComponentsContent:
      type: object
      properties:
        components:
          type: object
          properties:
            body:
              type: array
              items:
                anyOf:
                  - $ref: '#/components/schemas/ViberTextContent'
                  - $ref: '#/components/schemas/ViberImageContent'
                  - $ref: '#/components/schemas/ViberButtonContent'
    ViberImage:
      type: object
      properties:
        url:
          type: string
    ViberButton:
      type: object
      properties:
        caption:
          type: string
        url:
          type: string
    ViberChannelResponse:
      $ref: './configurations.yaml#/components/schemas/ViberChannelResponse'
    ViberChannelResponses:
      $ref: './configurations.yaml#/components/schemas/ViberChannelResponses'
    ChannelCallback:
      $ref: './configurations.yaml#/components/schemas/ChannelCallback'